service: slack-bot

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2

package:
  include:
    - functions

functions:

  command:
    handler: handler.command
    memorySize: 128
    events:
      - http:
          path: command
          method: post
          response:
            template: ${file(empty.vtl)}


  action:
    handler: handler.action
    memorySize: 128
    events:
      - http:
          path: action
          method: post
          request:
            template:
              application/x-www-form-urlencoded: ${file(action.vtl)}
          response:
            template: ${file(empty.vtl)}

  event:
    handler: handler.event
    memorySize: 128
    events:
      - http:
          path: event
          method: post

  callback:
    handler: handler.callback
    memorySize: 128
    events:
      - http:
          path: callback
          method: post

#   you can add any of the following events

#     - s3: ${bucket}
#     - schedule: rate(10 minutes)
#     - sns: greeter-topic

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
